import {
  Inter
} from 'next/font/google'

import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.css'
const inter = Inter({
  subsets: ['latin']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}) {
  return (<
    html lang="en" >
    <
    body className={
        inter.className
      } > {
        children
      } < /body> <
    script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous" > < /script> <
    /
    html >
        )
}